<?php

declare(strict_types=1);

namespace Fnlla\Php\Tests;

use Fnlla\Php\Support\UpgradeAnalyzer;
use PHPUnit\Framework\TestCase;
use ReflectionMethod;

final class UpgradeReadinessTest extends TestCase
{
    public function testBusinessBlueprintMatchesTheCurrentSourceEdition(): void
    {
        $check = (new ReflectionMethod(UpgradeAnalyzer::class, "checkBusinessReferenceBlueprint"))
            ->invoke(new UpgradeAnalyzer());
        self::assertSame("pass", $check["status"], $check["detail"]);
    }

    public function testIntegrationNamesAreAllowedButToolAuthorshipNoticesAreReported(): void
    {
        $root = sys_get_temp_dir() . "/fnlla-readiness-" . bin2hex(random_bytes(8));
        mkdir($root, 0700);
        $method = new ReflectionMethod(UpgradeAnalyzer::class, "checkAssistantVendorMarkers");
        $analyzer = new UpgradeAnalyzer();
        try {
            file_put_contents($root . "/README.md", "Optional OpenAI API and Anthropic API integrations.\n"
                . "Claude model configuration requires API access.\nCreated and maintained by TechAyo.\n");
            self::assertSame("pass", $method->invoke($analyzer, $root)["status"]);
            foreach (["Co" . "dex", "Open" . "AI", "Clau" . "de"] as $tool) {
                file_put_contents($root . "/notice.md", "Generated by " . $tool);
                $check = $method->invoke($analyzer, $root);
                self::assertSame("fail", $check["status"]);
                self::assertSame(["notice.md"], $check["data"]["files"]);
            }
            unlink($root . "/notice.md");
            self::assertSame("pass", $method->invoke($analyzer, $root)["status"]);
        } finally {
            foreach (["README.md", "notice.md"] as $name) {
                if (is_file($root . "/" . $name)) { unlink($root . "/" . $name); }
            }
            rmdir($root);
        }
    }
}
