#!/usr/bin/env php
<?php

declare(strict_types=1);

/*
===============================================================================
FNLLA PROJECT LAUNCHER
File: fnlla
Purpose:
- Boots the exported FNLLA project console and exposes downstream-safe commands.
===============================================================================
*/

use Fnlla\Php\Console\Commands\AiAskCommand;
use Fnlla\Php\Console\Commands\AiBriefCommand;
use Fnlla\Php\Console\Commands\AiExplainLogCommand;
use Fnlla\Php\Console\Commands\AiTriageCommand;
use Fnlla\Php\Console\Commands\BackupPlanCommand;
use Fnlla\Php\Console\Commands\ConfigDoctorCommand;
use Fnlla\Php\Console\Commands\DeveloperInstallStorageCommand;
use Fnlla\Php\Console\Commands\DeveloperRecoveryLinkCommand;
use Fnlla\Php\Console\Commands\ReleaseManifestCommand;
use Fnlla\Php\Console\Commands\TechDebtUpdateCommand;
use Fnlla\Php\Console\Commands\AiContextCommand;
use Fnlla\Php\Console\Commands\AiProvidersCommand;
use Fnlla\Php\Console\Commands\AiRedactCommand;
use Fnlla\Php\Console\Commands\AiReviewPackCommand;
use Fnlla\Php\Console\Commands\AiUpgradeBriefCommand;
use Fnlla\Php\Console\Commands\AppMapCommand;
use Fnlla\Php\Console\Commands\CacheClearCommand;
use Fnlla\Php\Console\Commands\ConfigCacheCommand;
use Fnlla\Php\Console\Commands\DoctorCommand;
use Fnlla\Php\Console\Commands\FnllaRuntimeSyncCommand;
use Fnlla\Php\Console\Commands\FnllaRuntimeValidateCommand;
use Fnlla\Php\Console\Commands\FrameworkUpdateCommand;
use Fnlla\Php\Console\Commands\MigrateCommand;
use Fnlla\Php\Console\Commands\MigrateRollbackCommand;
use Fnlla\Php\Console\Commands\MigrateStatusCommand;
use Fnlla\Php\Console\Commands\OptimizeClearCommand;
use Fnlla\Php\Console\Commands\OptimizeCommand;
use Fnlla\Php\Console\Commands\OptimizeWarmCommand;
use Fnlla\Php\Console\Commands\PerfBaselineUpdateCommand;
use Fnlla\Php\Console\Commands\PerfBudgetCommand;
use Fnlla\Php\Console\Commands\PerfCompareCommand;
use Fnlla\Php\Console\Commands\PerfProfileCommand;
use Fnlla\Php\Console\Commands\ProjectAcceptanceCommand;
use Fnlla\Php\Console\Commands\ProjectClaimCommand;
use Fnlla\Php\Console\Commands\QueueWorkCommand;
use Fnlla\Php\Console\Commands\ReleaseChecksumsCommand;
use Fnlla\Php\Console\Commands\ReleasePrepareCommand;
use Fnlla\Php\Console\Commands\ReleaseSbomCommand;
use Fnlla\Php\Console\Commands\RouteCacheCommand;
use Fnlla\Php\Console\Commands\RouteListCommand;
use Fnlla\Php\Console\Commands\ScheduleRunCommand;
use Fnlla\Php\Console\Commands\SecurityAuditCommand;
use Fnlla\Php\Console\Commands\SeedCommand;
use Fnlla\Php\Console\Commands\UpgradeApplyCommand;
use Fnlla\Php\Console\Commands\UpgradeCheckCommand;
use Fnlla\Php\Console\Commands\UpgradePlanCommand;
use Fnlla\Php\Console\Commands\VersionStatusCommand;
use Fnlla\Php\Console\Commands\VersionSyncCommand;

if (in_array($_SERVER["argv"][1] ?? "", ["fnlla-runtime:sync", "fnlla-runtime:validate", "framework:update", "version:status", "version:sync"], true) && !defined("FNLLA_RUNTIME_SKIP_AUTO_GUARD")) {
    define("FNLLA_RUNTIME_SKIP_AUTO_GUARD", true);
}

$container = require __DIR__ . DIRECTORY_SEPARATOR . "bootstrap" . DIRECTORY_SEPARATOR . "console.php";

$console = $container->make(\Fnlla\Php\Console\Application::class);
$console->register(AiAskCommand::class);
$console->register(AiBriefCommand::class);
$console->register(AiExplainLogCommand::class);
$console->register(AiTriageCommand::class);
$console->register(BackupPlanCommand::class);
$console->register(ConfigDoctorCommand::class);
$console->register(DeveloperInstallStorageCommand::class);
$console->register(DeveloperRecoveryLinkCommand::class);
$console->register(ReleaseManifestCommand::class);
$console->register(TechDebtUpdateCommand::class);
$console->register(AiContextCommand::class);
$console->register(AiProvidersCommand::class);
$console->register(AiRedactCommand::class);
$console->register(AiReviewPackCommand::class);
$console->register(AiUpgradeBriefCommand::class);
$console->register(AppMapCommand::class);
$console->register(CacheClearCommand::class);
$console->register(ConfigCacheCommand::class);
$console->register(DoctorCommand::class);
$console->register(FnllaRuntimeSyncCommand::class);
$console->register(FnllaRuntimeValidateCommand::class);
$console->register(FrameworkUpdateCommand::class);
$console->register(SeedCommand::class);
$console->register(MigrateRollbackCommand::class);
$console->register(MigrateCommand::class);
$console->register(MigrateStatusCommand::class);
$console->register(OptimizeClearCommand::class);
$console->register(OptimizeCommand::class);
$console->register(OptimizeWarmCommand::class);
$console->register(PerfBaselineUpdateCommand::class);
$console->register(PerfBudgetCommand::class);
$console->register(PerfCompareCommand::class);
$console->register(PerfProfileCommand::class);
$console->register(ProjectAcceptanceCommand::class);
$console->register(ProjectClaimCommand::class);
$console->register(QueueWorkCommand::class);
$console->register(ReleaseChecksumsCommand::class);
$console->register(ReleasePrepareCommand::class);
$console->register(ReleaseSbomCommand::class);
$console->register(RouteCacheCommand::class);
$console->register(RouteListCommand::class);
$console->register(ScheduleRunCommand::class);
$console->register(SecurityAuditCommand::class);
$console->register(UpgradeApplyCommand::class);
$console->register(UpgradeCheckCommand::class);
$console->register(UpgradePlanCommand::class);
$console->register(VersionStatusCommand::class);
$console->register(VersionSyncCommand::class);

foreach (["MakeController", "MakeMiddleware", "MakeCommand", "MakeFactory", "MakeSeeder", "MakeMigration"] as $command) {
    $console->register("Fnlla\\Php\\Console\\Commands\\" . $command . "Command");
}

exit($console->run($_SERVER["argv"] ?? []));
