<?php

declare(strict_types=1);

/*
===============================================================================
FNLLA SUPPORT SOURCE
File: src\Support\PreloadBuilder.php
Copyright (c) 2026 TechAyo LTD (techayo.co.uk). Released under the MIT License.
===============================================================================

Purpose:
- Generates an optional OPcache preload file for production runtimes.
*/

namespace Fnlla\Php\Support;

use FilesystemIterator;
use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;

final class PreloadBuilder
{
    public function build(string $outputPath): array
    {
        $files = [];

        foreach (["src", "bootstrap"] as $directory) {
            $absolute = base_path($directory);

            if (!is_dir($absolute)) {
                continue;
            }

            $iterator = new RecursiveIteratorIterator(
                new RecursiveDirectoryIterator($absolute, FilesystemIterator::SKIP_DOTS)
            );

            foreach ($iterator as $item) {
                if ($item->isFile() && str_ends_with($item->getFilename(), ".php")) {
                    $files[] = $item->getPathname();
                }
            }
        }

        sort($files);
        $lines = [
            "<?php",
            "",
            "declare(strict_types=1);",
            "",
            "/* Generated by `php fnlla optimize:warm`. Configure opcache.preload to this file when your hosting model supports it. */",
        ];

        foreach ($files as $file) {
            $lines[] = "require_once " . var_export($file, true) . ";";
        }

        $directory = dirname($outputPath);

        if (!is_dir($directory)) {
            mkdir($directory, 0777, true);
        }

        file_put_contents($outputPath, implode(PHP_EOL, $lines) . PHP_EOL, LOCK_EX);

        return [
            "path" => $outputPath,
            "files" => count($files),
        ];
    }
}
